version: '3.8'
services:
  postgresql:
    image: postgres:12-alpine
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_DB=rush_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - rush_psql:/var/lib/postgresql/data
  application:
    build:
      context: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgresql/rush_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
volumes:
  rush_psql: