version: '3.3'
services:
  application:
    image: rush:0.0.1
    container_name: rush
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/rush_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:12-alpine
    container_name: rush-postgres
    environment:
      - POSTGRES_DB=rush_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - rush_psql:/var/lib/postgresql/data
volumes:
  rush_psql: